[package]
name = "tren"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clippy = "0.0.302"
csv = "1.3.1"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
